vscode:
  extensions:
    - dbaeumer.vscode-eslint@1.9.1:YVcwmzKVVl+zZ+wMB02GjQ==
    - CoenraadS.bracket-pair-colorizer-2@0.0.28:Ht+NwW5So3KSfIJU7UX83A==
    - donjayamanne.githistory@0.4.6:roDZW3cK0MQ3dyhssMrtcg==
    - octref.vetur@0.22.6:xXCsvthKcTcJhinOkpQTjQ==